package handlers

import (
	"backend/internal/queue"
	"backend/internal/ws"
	"backend/models"
	"backend/services"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/gorilla/websocket"
	"github.com/labstack/echo/v4"
)

// Handler holds all service dependencies
type Handler struct {
	Spotify *services.SpotifyService
	YouTube *services.YouTubeService
	Queue   *queue.Queue
	Hub     *ws.Hub
}

var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool { return true },
}

// --- Asynchronous / Queue Handlers ---

// StartPlaylistDownload (POST /playlist/:id/download)
// Adds a job to the queue and returns the Job ID for WebSocket connection
func (h *Handler) StartPlaylistDownload(c echo.Context) error {
    id := c.Param("id")
    jobID := uuid.New().String()

    // Add to queue
    h.Queue.AddJob(models.Job{
        ID:         jobID,
        PlaylistID: id,
        Type:       "playlist", // or models.JobTypePlaylist
    })

    // Return the typed response
    return c.JSON(http.StatusAccepted, models.DownloadJobResponse{
        JobID: jobID,
        WsURL: "/api/ws?job_id=" + jobID,
    })
}

// HandleWebSocket (GET /ws)
// Upgrades connection and registers it to the specific Job ID
func (h *Handler) HandleWebSocket(c echo.Context) error {
	jobID := c.QueryParam("job_id")
	if jobID == "" {
		return c.String(http.StatusBadRequest, "Missing job_id")
	}

	wsConn, err := upgrader.Upgrade(c.Response(), c.Request(), nil)
	if err != nil {
		return err
	}

	h.Hub.Register(jobID, wsConn)
	return nil
}

// ServeDownloadFile (GET /download/:jobId)
// Serves the final ZIP file generated by the worker
func (h *Handler) ServeDownloadFile(c echo.Context) error {
	jobID := c.Param("jobId")
	// Ensure you validate this path in production to prevent traversal attacks
	filePath := fmt.Sprintf("./tmp/%s.zip", jobID)
	return c.File(filePath)
}