services:
  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    restart: always
    env_file:
      - .env 

  backend:
    build: ./backend
    container_name: go_backend
    restart: always
    env_file:
      - .env 
    volumes:
      - ./backend/storage:/root/storage # Persist storage if needed

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80" # Opens port 80 on your computer
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
