// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export type JobType = string;
export const JobTypePlaylist: JobType = "playlist";
export const JobTypeTrack: JobType = "track";
export const JobTypeAlbum: JobType = "album";
export type ProgressType = string;
export const ProgressTypeProgress: ProgressType = "progress";
export const ProgressTypeComplete: ProgressType = "complete";
export const ProgressTypeError: ProgressType = "error";
/**
 * AudioFormat controls whether yt-dlp's audio is re-encoded to MP3 (so we can
 * tag it) or kept as whatever native codec YouTube served (faster, untagged).
 */
export type AudioFormat = string;
export const AudioFormatMP3: AudioFormat = "mp3";
export const AudioFormatOriginal: AudioFormat = "original";
/**
 * AudioQuality selects an MP3 encode target. Only meaningful when
 * AudioFormat is "mp3" — YouTube's own source rarely exceeds ~160kbps, so
 * "high" intentionally has no fixed kbps claim; see WriteMP3Metadata's caller.
 */
export type AudioQuality = string;
export const QualityLow: AudioQuality = "low";
export const QualityMedium: AudioQuality = "medium";
export const QualityHigh: AudioQuality = "high";
/**
 * CoverMode controls where cover art ends up. Only offered for album jobs —
 * a playlist mixes tracks from different albums, so collapsing to one shared
 * folder image would lose real per-track art.
 */
export type CoverMode = string;
export const CoverEmbedded: CoverMode = "embedded";
export const CoverFolder: CoverMode = "folder";
export interface DownloadOptions {
  format: 'mp3' | 'original';
  quality: 'low' | 'medium' | 'high';
  coverMode: 'embedded' | 'folder';
  includeM3u: boolean;
}
export interface Job {
  id: string;
  itemId: string;
  type: 'playlist' | 'track' | 'album';
  options: DownloadOptions;
}
export interface ProgressMessage {
  type: 'progress' | 'complete' | 'error';
  jobId: string;
  progress: number /* float64 */; // 0-100
  message: string;
  payload?: unknown;
}
export interface DownloadJobResponse {
  job_id: string;
  ws_url: string;
}
export interface PlaylistResponse {
  metadata?: PlaylistMetadata;
  tracks: TrackDTO[];
  total: number /* int */;
}
export interface PlaylistMetadata {
  id: string;
  name: string;
  description: string;
  owner: string;
  imageUrl: string;
  externalUrl: string;
}
export interface TrackDTO {
  id: string;
  name: string;
  artists: ArtistDTO[];
  album: AlbumDTO;
  durationMs: number /* int */;
  explicit: boolean;
  previewUrl: string;
  externalUrl: string;
  addedAt: string;
  trackNumber: number /* int */;
  discNumber: number /* int */;
  isrc?: string;
}
export interface TrackDetailsDTO {
  id: string;
  name: string;
  artists: ArtistDTO[];
  album: AlbumDTO;
  durationMs: number /* int */;
  explicit: boolean;
  previewUrl: string;
  externalUrl: string;
  popularity: number /* int */;
  trackNumber: number /* int */;
  discNumber: number /* int */;
  isrc: string;
}
export interface ArtistDTO {
  name: string;
  id: string;
}
export interface AlbumDTO {
  id?: string;
  name: string;
  imageUrl: string;
  releaseDate: string;
  totalTracks?: number /* int */;
  label?: string;
  copyright?: string;
}
export interface AlbumMetadata {
  id: string;
  name: string;
  artists: ArtistDTO[];
  imageUrl: string;
  releaseDate: string;
  totalTracks: number /* int */;
  externalUrl: string;
}
export interface AlbumResponse {
  metadata?: AlbumMetadata;
  tracks: TrackDTO[];
  total: number /* int */;
}
/**
 * YtDlpResult represents the JSON output from yt-dlp
 * Moved here from youtube.go
 */
export interface YtDlpResult {
  id: string;
  title: string;
  duration: number /* float64 */;
  webpageUrl: string;
}
