// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export type JobType = string;
export const JobTypePlaylist: JobType = "playlist";
export const JobTypeTrack: JobType = "track";
export type ProgressType = string;
export const ProgressTypeProgress: ProgressType = "progress";
export const ProgressTypeComplete: ProgressType = "complete";
export const ProgressTypeError: ProgressType = "error";
export interface Job {
  id: string;
  playlistId: string;
  type: 'playlist' | 'track';
}
export interface ProgressMessage {
  type: 'progress' | 'complete' | 'error';
  jobId: string;
  progress: number /* float64 */; // 0-100
  message: string;
  payload?: unknown;
}
export interface DownloadJobResponse {
  job_id: string;
  ws_url: string;
}
export interface PlaylistResponse {
  metadata?: PlaylistMetadata;
  tracks: TrackDTO[];
  total: number /* int */;
}
export interface PlaylistMetadata {
  id: string;
  name: string;
  description: string;
  owner: string;
  imageUrl: string;
  externalUrl: string;
}
export interface TrackDTO {
  id: string;
  name: string;
  artists: ArtistDTO[];
  album: AlbumDTO;
  durationMs: number /* int */;
  explicit: boolean;
  previewUrl: string;
  externalUrl: string;
  addedAt: string;
}
export interface TrackDetailsDTO {
  id: string;
  name: string;
  artists: ArtistDTO[];
  album: AlbumDTO;
  durationMs: number /* int */;
  explicit: boolean;
  previewUrl: string;
  externalUrl: string;
  popularity: number /* int */;
  trackNumber: number /* int */;
  discNumber: number /* int */;
  isrc: string;
}
export interface ArtistDTO {
  name: string;
  id: string;
}
export interface AlbumDTO {
  name: string;
  imageUrl: string;
  releaseDate: string;
}
/**
 * YtDlpResult represents the JSON output from yt-dlp
 * Moved here from youtube.go
 */
export interface YtDlpResult {
  id: string;
  title: string;
  duration: number /* float64 */;
  webpageUrl: string;
}
